version: "3"
services:
  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
    container_name: db-server
  api-mockup:
    build:
      context: ./api-mockup
      dockerfile: Dockerfile
    volumes:
      - ./api-mockup/app:/app
    ports:
      - ${API_PORT}:80
    container_name: api-mockup
    tty: true

volumes:
  db-store:

